### ISSUE TITLE
GTK3 installation does not guarantee GTK2 installation

### ISSUE THREAD

**Issue by dhruvildave** [Meet-Modi/InternetTv-IPmulticast-Stream-radio#1]
In the README, it's mentioned that `libgtk-3-dev` will also install `libgtk2.0-dev` but that is not always guaranteed. So it needs to be installed seperately.

**Comment by Meet-Modi** [comment]
True, Applications based on gtk2 or gtk3 dont need any kind of installation. You need this library for just compiling and using libgtk-3-dev will do the job for both. However, it is always good to install both.
